name = "ocean-currents-proxy"
main = "proxy-worker.js"
compatibility_date = "2024-01-01"
workers_dev = true

# Account details 
account_id = "6f08cd01caaee709588f3568a5c8cc6f"

# Routes (optional - if you have a custom domain later)
# routes = [
#   { pattern = "proxy.yourdomain.com/*", zone_id = "your-zone-id" }
# ]

# Environment variables (if needed)
# [vars]
# UPSTREAM_URL = "https://coral.apl.uw.edu"

# Note: CPU limits are only available on paid plans
# Removed [limits] section for free plan compatibility

# Build configuration
[build]
command = ""
# Note: watch_paths is not a valid field in build section
